// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-2OUefrV7ZiSzDOT2YzXk6A_gmXx6Nv8',
    appId: '1:333300855496:web:addbfe7ee06475aaecebfd',
    messagingSenderId: '333300855496',
    projectId: 'final-489a1',
    authDomain: 'final-489a1.firebaseapp.com',
    storageBucket: 'final-489a1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH1Zccs0yeoFhgvM5COMWK4OqZxpOulRg',
    appId: '1:333300855496:android:fba1a54a486f2f75ecebfd',
    messagingSenderId: '333300855496',
    projectId: 'final-489a1',
    storageBucket: 'final-489a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhuUfh-weQpSyWMRAck2WM_vCxq-L4w6g',
    appId: '1:333300855496:ios:be8b8f2902f42d48ecebfd',
    messagingSenderId: '333300855496',
    projectId: 'final-489a1',
    storageBucket: 'final-489a1.appspot.com',
    iosClientId: '333300855496-eoev3uj253vnkf5m9davvuf22hguvoo7.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalAppProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhuUfh-weQpSyWMRAck2WM_vCxq-L4w6g',
    appId: '1:333300855496:ios:f9c2f2f8a687f4ececebfd',
    messagingSenderId: '333300855496',
    projectId: 'final-489a1',
    storageBucket: 'final-489a1.appspot.com',
    iosClientId: '333300855496-koc28m1n70jeupm2c3ej67r4h1ord90o.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalAppProject.RunnerTests',
  );
}
